services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      # Mount source code for hot reloading/editing without rebuilds
      - ./dataset:/app/dataset
      - ./src:/app/src
      - ./models:/app/models
      - ./input_images:/app/input_images
    environment:
      - APP_ENV=development
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    # Increase shared memory for PyTorch data loaders
    shm_size: '8gb'
    ports:
      - "5678:5678"
    # Enable GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # Command to run with debugpy listening
    command: python -m debugpy --listen 0.0.0.0:5678 src/main.py train --epochs 30 --patience 30 --batch 16
