import logging
from pathlib import Path
from typing import List, Dict, Any
from ultralytics import YOLO

logger = logging.getLogger(__name__)

class ThreatMapper:
    """
    Maps architecture components to STRIDE threats.
    
    STRIDE stands for:
    - Spoofing
    - Tampering
    - Repudiation
    - Information Disclosure
    - Denial of Service
    - Elevation of Privilege
    """

    # Knowledge base of threats per component type
    THREAT_KB = {
        'aws_amazon_api_gateway': [
            "Spoofing: Unidentified API calls.",
            "Denial of Service: API rate limit exhaustion.",
            "Information Disclosure: Unencrypted API response.",
            "Tampering: Injection attacks via API parameters."
        ],
        'aws_lambda_lambda_function': [
            "Tampering: Malicious code injection.",
            "Denial of Service: Concurrency limit exhaustion.",
            "Elevation of Privilege: Over-permissive IAM roles."
        ],
        'azure_sql_server': [
            "Tampering: SQL Injection.",
            "Information Disclosure: Data leakage from unencrypted storage.",
            "Denial of Service: Database connection saturation.",
            "Repudiation: Insufficient audit logs."
        ],
        'gcp_cloud_storage': [
            "Information Disclosure: Publicly accessible bucket.",
            "Tampering: Unauthorized file modification.",
            "Denial of Service: Excessive request costs."
        ],
        # Fallback for generic or unknown components
        'default': [
            "Spoofing: Ensure authentication is enforced.",
            "Tampering: Validate integrity of inputs.",
            "Information Disclosure: Encrypt sensitive data."
        ]
    }

    @staticmethod
    def get_threats(component: str) -> List[str]:
        """
        Retrieves threats for a specific component.

        Args:
            component (str): The class name of the component (e.g., aws_amazon_api_gateway).

        Returns:
            List[str]: List of potential threats.
        """
        threats = ThreatMapper.THREAT_KB.get(component)
        if not threats:
            # Try to match partial keys or return default
            for key, val in ThreatMapper.THREAT_KB.items():
                if key in component:
                    return val
            return ThreatMapper.THREAT_KB['default']
        return threats


class ThreatModeler:
    """
    Orchestrates the threat modeling process using YOLO inference.
    """

    def __init__(self, model_path: Path):
        """
        Args:
            model_path (Path): Path to the trained .pt model file.
        """
        self.model_path = model_path
        if not self.model_path.exists():
            raise FileNotFoundError(f"Model file not found: {self.model_path}")
        self.model = YOLO(self.model_path)

    def analyze_image(self, image_path: Path, conf_threshold: float = 0.25) -> List[Dict[str, Any]]:
        """
        Runs inference on an image and maps results to threats.

        Args:
            image_path (Path): Path to the image file.
            conf_threshold (float): Confidence threshold for detections.

        Returns:
            List[Dict[str, Any]]: List of detected objects with their threats.
        """
        results = self.model.predict(source=str(image_path), conf=conf_threshold)
        
        analysis_report = []
        
        for result in results:
            for box in result.boxes:
                # Get class ID and Confidence
                cls_id = int(box.cls[0])
                confidence = float(box.conf[0])
                
                # Get class name
                class_name = self.model.names[cls_id]
                
                # Map to threats
                threats = ThreatMapper.get_threats(class_name)
                
                analysis_report.append({
                    "component": class_name,
                    "confidence": confidence,
                    "threats": threats,
                    "bbox": box.xywh.tolist() # x, y, w, h
                })
                
        return analysis_report

    def generate_report(self, analysis: List[Dict[str, Any]], output_path: Path) -> None:
        """
        Generates a readable Markdown report.

        Args:
            analysis (List[Dict[str, Any]]): The analysis results.
            output_path (Path): Path where the report will be saved.
        """
        with open(output_path, 'w') as f:
            f.write("# Automated Threat Model Report\n\n")
            f.write("Generated by STRIDE-YOLO System\n\n")
            
            if not analysis:
                f.write("No components detected.\n")
                return

            for item in analysis:
                f.write(f"## Component: **{item['component']}**\n")
                f.write(f"- **Confidence**: {item['confidence']:.2f}\n")
                f.write("- **Potential Threats (STRIDE)**:\n")
                for threat in item['threats']:
                    f.write(f"  - {threat}\n")
                f.write("\n---\n")
        logger.info(f"Report report saved to {output_path}")
